((emacs-lisp-mode . ((fill-column . 70)
                     (indent-tabs-mode . nil)
                     (elisp-lint-indent-specs . ((vulpea-utils-with-file . 1)
                                                 (vulpea-utils-with-note . 1)
                                                 (org-with-point-at . 1)
                                                 (org-element-map . 2)))))
 (org-mode . ((vulpea-id-auto-targets . nil))))
